Add support for CUDA builds on Windows (take two)
conda-forge/onnxruntime-feedstock pull request #121
Opened 2024-05-25 07:14 UTC by traversaro

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-05-25 07:17 UTC, traversaro commented
@conda-forge-admin, please rerender

2024-05-26 00:01 UTC, traversaro commented
@conda-forge-admin, please rerender

2024-05-26 17:24 UTC, traversaro commented
@conda-forge-admin, please rerender

2024-05-27 11:25 UTC, traversaro commented
@conda-forge/onnxruntime the PR is ready for review. There was a Linux failure, but as this PR does not modify anything of Linux related, I guess this is a non-deterministic error? Anyhow, it would be great to restart only that job to avoid relaunching all 100 jobs just to restart that job.

2024-05-27 20:46 UTC, hmaarrfk commented
The interface may provide you with a "restart failed jobs". Typically this becomes visible when all jobs have come to a conclusion. Though what you see and what I see may be different.

2024-05-27 22:00 UTC, traversaro commented
> The interface may provide you with a "restart failed jobs". Typically this becomes visible when all jobs have come to a conclusion. Though what you see and what I see may be different.

Yes, I think that is available only for admin of the repo.

2024-05-28 12:11 UTC, traversaro commented
Not sure who restarted the failing job, but now they are all clean.

2024-05-28 12:49 UTC, hmaarrfk commented
> but now they are all green.

(I did)

2024-05-28 12:51 UTC, hmaarrfk requested changes
Could we cherry pick the numpy checks from:
https://github.com/conda-forge/onnxruntime-feedstock/pull/123

mine can all be squashed if you want or just rewritten with your authorship.

2024-05-30 11:43 UTC, merged